name       : kdbusaddons
version    : 5.64.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kdbusaddons-5.64.0.tar.xz : 74a6eb443a74eb74a859238b555a3b16be1d6367c4db2a7af5b16da528d57f62
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
