name       : kdbusaddons
version    : 5.55.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kdbusaddons-5.55.0.tar.xz : f4b0573cc45db3fb15913eb37b4931f95cffd7d6ebc0b98a817144f6986743ea
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
