name       : kdbusaddons
version    : 5.92.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/kdbusaddons-5.92.0.tar.xz : 7c03f33cc49ffa80e509f654f410cb142e917bceb2f35f08836dc46ed268ae54
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
