name       : kdbusaddons
version    : 5.61.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/kdbusaddons-5.61.0.tar.xz : f24fadc71670591bb679cde68147e53819f6c3d56126ecbafe59688fc47b347d
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
