name       : kdbusaddons
version    : 5.54.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kdbusaddons-5.54.0.tar.xz : 6e7d5adb73fe7c8780b9264c37198f23d1edf2361fdb47c0257ef0c1f0d574bb
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
