name       : kdbusaddons
version    : 5.59.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kdbusaddons-5.59.0.tar.xz : c3c8ff00653e587448013f00f0797d6d78d64e00f0d92b9647cc81d07b54a20b
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
