name       : kdbusaddons
version    : 5.44.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kdbusaddons-5.44.0.tar.xz : 6f7e8ccb12f243fadb881b7b958000081b89ee115b43d5a0d067e7b9a3b76795
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
