name       : kdbusaddons
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/kdbusaddons-5.35.0.tar.xz : 15fb73e9987b95fc4db7968bcd45bf08ec47179347e9ba856e26ba61b8e296c1
license    : LGPL-2.1
component  : programming
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
