name       : kdbusaddons
version    : 5.83.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kdbusaddons-5.83.0.tar.xz : 0a0f04c3a104e3c6be33adea27d80d67ad73f05d584252d4496e88da11974905
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
