name       : kdbusaddons
version    : 5.48.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kdbusaddons-5.48.0.tar.xz : 39a3df3ad2092cc0a551356e45209a51b312abb5632e17b51b648b222323ed6e
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
