name       : kdbusaddons
version    : 5.65.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kdbusaddons-5.65.0.tar.xz : e2777538c6d1f0dd5956b3bc2c9cfe34fe360655c188e658f52f926ff8cb3fcc
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
