name       : kdbusaddons
version    : 5.50.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kdbusaddons-5.50.0.tar.xz : d54fbcec8709a6f4307b85c5e75e91d6ac96b441e0c13b0cd88ec89324795b46
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
