name       : kdbusaddons
version    : 5.43.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kdbusaddons-5.43.0.tar.xz : 65f72eb0ce7ebddc46f196a3ff6ddf3493465d80b3cffa3ddecf2a16543695c0
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
