name       : kdbusaddons
version    : 5.39.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.39/kdbusaddons-5.39.0.tar.xz : 23477be1a3271d599be896477253fbcd9895ca8688ecb6771b290c5b522ae842
license    : LGPL-2.1
component  : programming
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
