name       : kdbusaddons
version    : 5.47.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kdbusaddons-5.47.0.tar.xz : 2bd65636ba6293e79f26195aa9273c6bbe7dbce580c879304b4babea6c064710
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
