name       : kdbusaddons
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/kdbusaddons-5.38.0.tar.xz : 1c1f8955570cd7e0480ec619084c5ea56cbffaca5307d9053d52092f10d589d7
license    : LGPL-2.1
component  : programming
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
