name       : kdbusaddons
version    : 5.56.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kdbusaddons-5.56.0.tar.xz : b930918ccece1d80aaf0eb770d4e17e5926d7da3a97d1f8506f28829d267b972
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
