name       : kdbusaddons
version    : 5.46.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kdbusaddons-5.46.0.tar.xz : c3ba307d651a2ac6842319cbab0a8686d0bb13eaba0f3faf7ee386460db0031e
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
