name       : kdbusaddons
version    : 5.72.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kdbusaddons-5.72.0.tar.xz : 5c8ee0f8e5741d6a934aa722874ba3d7f0d101f43bddc4e87c15320f289fa232
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
