name       : kdbusaddons
version    : 5.63.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kdbusaddons-5.63.0.tar.xz : 1b0ba356dd285b6785d14b91f17eb1bcb9c5c84f23ff5c8608954cb013cafc87
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
