name       : kdbusaddons
version    : 5.53.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kdbusaddons-5.53.0.tar.xz : d02b0cc7b881295333ba3cf265aae942bca510cf62e386cc949311396a20ee17
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
