name       : kdbusaddons
version    : 5.80.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kdbusaddons-5.80.0.tar.xz : 14924319878951a4fbbf7b93da22428274449bec2bdd93b092e89f11bfbc1bf0
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
optimize   :
    - lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
