name       : kdbusaddons
version    : 5.58.0
release    : 27
source     :
    - https://download.kde.org/stable/frameworks/5.58/kdbusaddons-5.58.0.tar.xz : 42f176b737f81e120d2fa78c20891b3b7e3f182c6e144ec9c99935a32d63f9b1
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
