name       : kdbusaddons
version    : 5.40.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kdbusaddons-5.40.0.tar.xz : 24a6268127bdfb5095d156f5251052e69a09523ec62499daa606c34f916feb27
license    : LGPL-2.1
component  : programming
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
