name       : kdbusaddons
version    : 5.42.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kdbusaddons-5.42.0.tar.xz : 6dc19471c9dc53ae13c642b3cd2512fdb2aadb6ab287caeffe56829307bb2398
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
