name       : kdbusaddons
version    : 5.25.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.25/kdbusaddons-5.25.0.tar.xz : 3db7b90f37ac78c813e2554ce48591b3535732207b1c94deed3a13aea554132e
license    : LGPL-2.1
component  : programming
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
