name       : kdbusaddons
version    : 5.67.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kdbusaddons-5.67.0.tar.xz : ae4795d1286c97f46be9121b2761f811e36f1c586cb030ed6debd97dc7c73518
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
