name       : kdbusaddons
version    : 5.32.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.32/kdbusaddons-5.32.0.tar.xz : 099872dc19e917ca7b172881ca547b4df7f62e1968fab805a540fd99b59425a8
license    : LGPL-2.1
component  : programming
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
