name       : kdbusaddons
version    : 5.79.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kdbusaddons-5.79.0.tar.xz : 2071c5a06226b77c4cb1d4e46b50258c980e57448fdbb1a49259db64a7a2539f
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
optimize   :
    - lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
