name       : kdbusaddons
version    : 5.52.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kdbusaddons-5.52.0.tar.xz : d757340e5727b6437dad5cdb5cbe51fe6d96c814c44279b774fe56e2b66e7db9
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
