name       : kdbusaddons
version    : 5.71.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kdbusaddons-5.71.0.tar.xz : b441f525248d9d675333cebedf97ee0232a3a9b7aa9aff84d825dfcdb3bcd23c
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
